kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: httpbin
spec:
  podSelector:
    matchLabels:
      app: httpbin
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: sleep
